/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#4F46E5',
        'on-primary': '#FFFFFF',
        'primary-container': '#EEF2FF',
        'primary-fixed': '#E0E7FF',
        'primary-fixed-dim': '#C7D2FE',
        'on-primary-fixed': '#1E1B4B',
        'on-primary-fixed-variant': '#4338CA',
        'inverse-primary': '#A5B4FC',
        secondary: '#0891B2',
        'on-secondary': '#FFFFFF',
        'secondary-container': '#CFFAFE',
        'secondary-fixed': '#CFFAFE',
        'secondary-fixed-dim': '#67E8F9',
        'on-secondary-container': '#155E75',
        'on-secondary-fixed': '#020617',
        'on-secondary-fixed-variant': '#0E7490',
        tertiary: '#7C3AED',
        'on-tertiary': '#FFFFFF',
        'tertiary-container': '#F5F3FF',
        'tertiary-fixed': '#EDE9FE',
        'tertiary-fixed-dim': '#DDD6FE',
        'on-tertiary-container': '#3B0764',
        'on-tertiary-fixed': '#1E0030',
        'on-tertiary-fixed-variant': '#6D28D9',
        error: '#DC2626',
        'on-error': '#FFFFFF',
        'error-container': '#FEE2E2',
        'on-error-container': '#7F1D1D',
        success: '#059669',
        'success-container': '#D1FAE5',
        background: '#F8FAFC',
        'on-background': '#0F172A',
        surface: '#FFFFFF',
        'on-surface': '#0F172A',
        'surface-dim': '#E2E8F0',
        'surface-bright': '#FFFFFF',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F1F5F9',
        'surface-container': '#E2E8F0',
        'surface-container-high': '#E2E8F0',
        'surface-container-highest': '#CBD5E1',
        'on-surface-variant': '#475569',
        outline: '#E2E8F0',
        'outline-variant': '#F1F5F9',
        'surface-variant': '#EEF2FF',
      },
      borderRadius: {
        lg: '0.5rem',
        xl: '0.75rem',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'label-md': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-xs': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'label-md': ['13px', { lineHeight: '16px', fontWeight: '500' }],
      },
      boxShadow: {
        'soft': '0 1px 3px 0 rgb(0 0 0 / 0.04)',
        'card': '0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.04)',
        'card-hover': '0 10px 25px -3px rgb(0 0 0 / 0.08), 0 4px 6px -4px rgb(0 0 0 / 0.04)',
        'elevated': '0 4px 6px -1px rgb(0 0 0 / 0.06), 0 2px 4px -2px rgb(0 0 0 / 0.04)',
      },
      animation: {
        'fade-in': 'fade-in 0.5s ease-out forwards',
        'slide-up': 'slide-up 0.5s ease-out forwards',
        'scale-in': 'scale-in 0.3s ease-out forwards',
        'fade-in-fast': 'fade-in 0.2s ease-out forwards',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
      maxWidth: {
        'max-width': '1440px',
      },
    },
  },
  plugins: [],
}
